import asyncio
import os
from playwright.async_api import async_playwright

class AIChatScraper:
    @staticmethod
    async def query_bot(provider: str, prompt: str) -> str:
        """
        Automates browser sessions via Playwright to securely prompt web LLMs
        and scrape responses, rendering generated imagery inline within the UI.
        """
        provider = provider.lower().strip()
        
        # Initialize component variables safely to avoid UnboundLocalError in the finally block
        context = None
        page = None
        final_output = "No response was generated by the target workspace engine."
        
        async with async_playwright() as p:
            try:
                # Target path pointing to your dedicated browser profile
                user_data_dir = r"C:\Users\kunda\AppData\Local\Google\Chrome\MarvisProfile"
                
                # ======================================================
                # --- CHROMIUM INITIALIZATION LAYER ---
                # ======================================================
                if provider in ["gemini", "chatgpt", "claude"]:
                    context = await p.chromium.launch_persistent_context(
                        user_data_dir,
                        headless=False,
                        channel="chrome",  # Connects directly to your installed Chrome binary
                        args=[
                            "--disable-blink-features=AutomationControlled",
                            "--profile-directory=Default"
                        ]
                    )
                    page = context.pages[0] if context.pages else await context.new_page()
                else:
                    return f"Unknown provider target: '{provider}'"

                # Set consistent user-agent tracking tags across all platforms
                await page.set_extra_http_headers({
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
                })

                # ======================================================
                # --- CHATGPT WORKFLOW ---
                # ======================================================
                if provider == "chatgpt":
                    await page.goto("https://chatgpt.com", wait_until="networkidle", timeout=60000)
                    
                    await page.wait_for_selector("#prompt-textarea", state="visible", timeout=30000)
                    await page.click("#prompt-textarea")
                    await asyncio.sleep(1.0)
                    
                    await page.fill("#prompt-textarea", prompt)
                    await asyncio.sleep(0.5)
                    await page.keyboard.press("Enter")
                    
                    await asyncio.sleep(4.5)  # Let generation get structurally underway
                    
                    try:
                        # Wait until the streaming buttons revert to a static ready state
                        if await page.locator('button[data-testid="stop-button"]').count() > 0:
                            await page.wait_for_selector('button[data-testid="stop-button"]', state="detached", timeout=90000)
                        else:
                            await page.wait_for_selector('button[data-testid="send-button"]', state="visible", timeout=90000)
                    except Exception:
                        await asyncio.sleep(5.0)
                    
                    selectors = [
                        'article div.markdown',
                        'div[data-message-author-role="assistant"]',
                        'main div.markdown'
                    ]
                    
                    messages = []
                    for selector in selectors:
                        messages = await page.locator(selector).all()
                        if messages:
                            break
                            
                    if messages:
                        response_text = await messages[-1].inner_text()
                        final_output = response_text
                        
                        if any(x in prompt.lower() for x in ["image", "generate", "draw"]):
                            img_locator = page.locator('main img[src^="blob:"], main img[src*="files.oaiusercontent.com"]').last
                            if await img_locator.count() > 0:
                                img_url = await img_locator.get_attribute("src")
                                final_output = f"{response_text}<br><br><img src='{img_url}' width='400' style='border-radius: 8px;'><br>"
                    else:
                        final_output = "Could not extract text block from ChatGPT layout."

                # ======================================================
                # --- GEMINI WORKFLOW ---
                # ======================================================
                elif provider == "gemini":
                    await page.goto("https://gemini.google.com/app", wait_until="networkidle", timeout=60000)
                    
                    await page.wait_for_selector(".ql-editor", state="visible", timeout=30000)
                    await page.click(".ql-editor")
                    await asyncio.sleep(1.0)
                    
                    await page.fill(".ql-editor", prompt)
                    await asyncio.sleep(0.5)
                    await page.keyboard.press("Enter")
                    
                    await asyncio.sleep(4.5)
                    
                    await page.wait_for_selector(".model-response-text:not(.generating)", timeout=90000)
                    
                    messages = await page.locator(".model-response-text").all()
                    if messages:
                        response_text = await messages[-1].inner_text()
                        final_output = response_text
                        
                        if any(x in prompt.lower() for x in ["image", "create", "generate"]):
                            img_locator = page.locator('.model-response-text img, .image-container img').last
                            if await img_locator.count() > 0:
                                img_url = await img_locator.get_attribute("src")
                                final_output = f"{response_text}<br><br><img src='{img_url}' width='400' style='border-radius: 8px;'><br>"
                    else:
                        final_output = "Could not extract text block from Gemini layout."

                # ======================================================
                # --- CLAUDE WORKFLOW ---
                # ======================================================
                elif provider == "claude":
                    await page.goto("https://claude.ai/chats", wait_until="networkidle", timeout=60000)
                    
                    await page.wait_for_selector('div[contenteditable="true"]', state="visible", timeout=30000)
                    await page.click('div[contenteditable="true"]')
                    await asyncio.sleep(1.0)
                    
                    await page.fill('div[contenteditable="true"]', prompt)
                    await asyncio.sleep(0.5)
                    await page.keyboard.press("Enter")
                    
                    await asyncio.sleep(4.5)
                    
                    try:
                        stop_btn = page.locator('button[aria-label="Stop Generating"], button[data-testid="stop-building"]')
                        if await stop_btn.count() > 0:
                            await stop_btn.wait_for(state="detached", timeout=90000)
                        else:
                            await asyncio.sleep(8.0)
                    except Exception:
                        await asyncio.sleep(6.0)
                    
                    messages = await page.locator('.font-claude-message, [data-testid="message-turn-assistant"] .markdown').all()
                    if messages:
                        final_output = await messages[-1].inner_text()
                    else:
                        final_output = "Could not extract text block from Claude layout."

            except Exception as e:
                final_output = f"Browser automation timed out or hit a wall: {str(e)}"
                
            finally:
                # Clean up the browser instance cleanly without crashing hanging processes
                if context:
                    try:
                        await context.close()
                    except Exception:
                        pass
                
                return final_output